# Generated by Django 5.1.5 on 2025-03-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
