# Generated by Django 5.1.5 on 2025-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_asset/default.jpg', null=True, upload_to='event_asset'),
        ),
    ]
